accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
]

developer_share_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('category/<str:subject>', views.category, name='category'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    birthday = models.DateField(null=True)
    pass

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label='유저 이름',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '유저 이름',
            }
        ),
    )
    password = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '비밀번호',
            }
        ),
    )
    class Meta(AuthenticationForm):
        model = get_user_model
        fields = ('username', 'password')


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='기존 비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '기존 비밀번호',
            }
        ),
    )
    new_password1 = forms.CharField(
        label='새 비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '새 비밀번호',
            }
        ),
    )
    new_password2 = forms.CharField(
        label='새 비밀번호 (확인)',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '새 비밀번호 (확인)',
            }
        ),
    )
    

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label='유저 이름',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '유저 이름',
            }
        ),
    )

    email = forms.EmailField(
        label='이메일',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이메일',
            }
        ),
    )

    first_name = forms.CharField(
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이름',
            }
        ),
    )

    last_name = forms.CharField(
        label='성',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '성',
            }
        ),
    )

    birthday = forms.DateField(
        label='생년월일',
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control',
                'placeholder': '생년월일',
            }
        ),
    )

    password1 = forms.CharField(
        label='비밀번호',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '비밀번호',
            }
        ),
    )
    password2 = forms.CharField(
        label='비밀번호 확인',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': '비밀번호 확인',
            }
        ),
    )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'birthday')


class CustomUserChangeForm(UserChangeForm):

    email = forms.EmailField(
        label='이메일',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이메일',
            }
        ),
    )

    first_name = forms.CharField(
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '이름',
            }
        ),
    )

    last_name = forms.CharField(
        label='성',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '성',
            }
        ),
    )

    birthday = forms.DateField(
        label='생년월일',
        widget=forms.DateInput(
            attrs={
                'type': 'date',
                'class': 'form-control',
                'placeholder': '생년월일',
            }
        ),
    )
    
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name', 'birthday')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields.pop('password')

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserChangeForm, CustomUserCreationForm, CustomPasswordChangeForm, CustomAuthenticationForm
# from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required

# Create your views here.


# 로그인
def login(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            if request.POST.get('next'):
                url = request.POST.get('next')
            else:
                url = 'posts:index'
            return redirect(url)
    else:
        form = CustomAuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


# 로그아웃
@login_required
def logout(request):
    auth_logout(request)
    return redirect('posts:index')


# 회원 가입
def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index') 
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


# 회원 정보 변경
@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('posts:index')
    else:
        form = CustomUserChangeForm(instance= request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


# 회원 탈퇴
@login_required
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('posts:index')


# 비밀번호 변경
@login_required
def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return redirect('posts:index')
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


# 프로필
@login_required
def profile(request):
    return render(request, 'accounts/profile.html')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex flex-column mt-5">
  
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link"  href="{% url 'accounts:update' %}">프로필 편집</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" aria-current="page" href="{% url 'accounts:change_password' %}">비밀번호 수정</a>
    </li>
  </ul>

  <div class="border p-5">
    <form action="{% url 'accounts:update' %}" method="POST">
      {% csrf_token %}
      {% for field in form %}
      <div class="input-group mb-3">
        <span class="input-group-text" id="{{ field.auto_id }}">{{ field.label }}</span>
        {{ field }}
      </div>
      {% endfor %}
      <div class="text-end">
        <input class="btn btn-primary" type="submit" value="수정">
      </div>
    </form>
  </div>

</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block style %}
#login {
  margin-top: 10rem;
}
{% endblock style %}

{% block content %}
  <div id="login">
    <div class="d-flex justify-content-center">
      <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="input-group mb-3">
          <span class="input-group-text" id="{{ field.auto_id }}">{{ field.label }}</span>
          {{ field }}
        </div>
        {% endfor %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <div class="d-grid">
          <input class="btn btn-success" type="submit" value="로그인">
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block style %}
  #profile-img {
    width: 10rem;
    height: 10rem;
  }
  img {
    width: auto;
    height: auto;
    object-fit: cover;
  }
  #detail {
    width: 40rem;
  }
{% endblock style %}

{% block content %}
<div class='d-flex flex-column align-items-center mt-5'>
  <div class="mb-5">
    <div id="profile-img" class="border rounded-circle position-relative">
      <img src="https://www.nasa.gov/sites/default/files/thumbnails/image/main_image_star-forming_region_carina_nircam_final-5mb.jpg" alt="" class="rounded-circle position-absolute top-50 start-50 translate-middle" style="width: 10rem; height: 10rem;">
    </div>
  </div>

  <div>
    <div class="d-flex justify-content-end">
      <div>
        <a class="dropdown-item" href="{% url 'accounts:update' %}">
          <div class="d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
              <i class="bi bi-pencil-square"></i>
            </svg>
            <span>프로필 편집</span>
          </div>
        </a>
      </div>
    </div>

    <table id="detail" class="table">    
      <tbody>
        <tr>
          <th scope="row">유저 이름</th>
          <td>{{ user.username }}</td>
        </tr>
        <tr>
          <th scope="row">이메일</th>
          <td>{{ user.email }}</td>
        </tr>
        <tr>
          <th scope="row">성</th>
          <td>{{ user.last_name }}</td>
        </tr>
        <tr>
          <th scope="row">이름</th>
          <td>{{ user.first_name }}</td>
        </tr>
        <tr>
          <th scope="row">생년월일</th>
          <td>{{ user.birthday }}</td>
        </tr>
        <tr>
          <th scope="row">마지막 로그인</th>
          <td>{{ user.last_login }}</td>
        </tr>
        <tr>
          <th scope="row">가입일</th>
          <td>{{ user.date_joined }}</td>
        </tr>
        <tr>
          <td class="border-0"></td>
          <td class="border-0">
            <div class="text-end">
              <form action="{% url 'accounts:delete' %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">회원탈퇴</button>
              </form>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

    

{% endblock content %}  

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block style %}
#signup {
  margin-top: 10rem;
}
{% endblock style %}

{% block content %}
  <div id="signup" class="d-flex justify-content-center">
    <form action="{% url 'accounts:signup' %}" method="POST">
      {% csrf_token %}
      {% for field in form %}
      <div class="input-group mb-3">
        <span class="input-group-text" id="{{ field.auto_id }}">{{ field.label }}</span>
        {{ field }}
      </div>
      {% endfor %}
      <div class="d-grid">
        <input class="btn btn-success" type="submit" value="회원 가입">
      </div>
    </form>
  </div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block style %}

{% endblock style %}

{% block content %}
  <div class="d-flex flex-column mt-5">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">프로필 편집</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:change_password' %}">비밀번호 수정</a>
      </li>
    </ul>

    <div class="border p-5">
      <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="input-group mb-3">
          <span class="input-group-text" id="{{ field.auto_id }}">{{ field.label }}</span>
          {{ field }}
        </div>
        {% endfor %}
        <div class="text-end">
          <input class="btn btn-primary" type="submit" value="수정">
        </div>
      </form>
    </div>
  </div>
{% endblock content %}