accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
]

developer_share_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('category/<str:subject>', views.category, name='category'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
  <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square.css" rel="stylesheet">
  <style>
    {% block style %}
    {% endblock style %}
    
    body {
      font-family: 'NanumSquareAcb';
    }
    
    a {
      text-decoration: none;
      color: black;
    }
    

    .index {
      padding-left: 30rem;
      padding-right: 15rem;
      padding-top: 5rem;
    }

    @media (max-width: 1750px) {
      .index {
        padding-left: 20rem;
        padding-right: 5rem;
        padding-top: 5rem;
      }
    }


    .sidebar {
      padding-top: 5rem;
      width: 15rem;
      position: fixed;
      z-index: 50;
      height: 100vh;
    }

    li {
      list-style-type: none;
    }
  </style>
</head>
<body>
  <!-- 네비게이션 바 -->
  {% include 'navbar.html' %}

  <!-- 사이드 바 -->
  {% include 'sidebar.html' %}
  
  <div class="index">
    {% block content %}
    {% endblock content %}
  </div>

  <script>
    // sidebar 캡슐
    const links = document.querySelectorAll("#sidebar li")    
    links.forEach((link) => {
      const liText = link.querySelector('#sidebar span')
      if (liText.textContent === '{{ subject }}') {
        link.classList.add("bg-white")
      }
    })

    // 시계
    const clock = document.getElementById("clock");
    const getClock = () => {
      const date = new Date()
      const hours = String(date.getHours()).padStart(2, "0")
      const minutes = String(date.getMinutes()).padStart(2, "0")
      const seconds = String(date.getSeconds()).padStart(2, "0")
      clock.innerText = `${hours}:${minutes}:${seconds}`
    }

    getClock()
    setInterval(getClock, 1000);

  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="fixed-top navbar navbar-expand-lg bg-body-secondary px-5">
  <div class="container-fluid">
    <div>
      <a class="navbar-brand" href="{% url 'posts:index' %}">Home</a>
    </div>

    <div>
      <h6 id="clock">00:00:00</h6>
    </div>
    
    <div class="d-flex align-items-center gap-2">
      {% if request.user.is_authenticated %}
      <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          {{ user }}
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">내 프로필</a></li>
          <li><a class="dropdown-item" href="{% url 'accounts:update' %}">프로필 편집</a></li>
          <li>
            <form action="{% url 'accounts:logout' %}" method="POST">
              {% csrf_token %}
              <button class="dropdown-item" type="submit" onclick="return confirm('로그아웃하시겠습니까?')">로그아웃</button>
            </form>
          </li>
          <li>
            <form action="{% url 'accounts:delete' %}" method="POST">
              {% csrf_token %}
              <button class="dropdown-item" type="submit" onclick="return confirm('탈퇴하시겠습니까?')">회원탈퇴</button>
            </form>
          </li>
        </ul>
      </div>

      {% else %}
      <a class="btn" href="{% url 'accounts:login' %}" type="submit">
        로그인
      </a>
      <a class="btn btn-success" href="{% url 'accounts:signup' %}">회원 가입</a>
      {% endif %}
    </div>
  </div>
</nav>

templates/sidebar.html
<div class="sidebar bg-body-secondary ps-3">
  <div class="text-center">
    <span class="fs-3"><a href="{% url 'posts:index' %}">IT 정보 공유</a></span>
    <hr>
  </div>
  
  <ul id='sidebar'>
    <li class="mb-3 fs-5 ps-3 py-2 rounded-start-pill">
      <a href="{% url 'posts:create' %}">
        <div class="d-flex align-items-center gap-2">
          <i class="bi bi-plus-square"></i>
          <span>글 작성</span>
        </div>
      </a>
    </li>
    <li class="mb-3 fs-5 ps-3 py-2 rounded-start-pill">
      <a href="{% url 'posts:index' %}">
        <div class="d-flex align-items-center gap-2">
          <i class="bi bi-file-earmark"></i>
          <span>모든 글</span>
        </div>
      </a>
    </li>
    <li class="mb-3 fs-5 ps-3 py-2 rounded-start-pill">
      <a href="{% url 'posts:category' '개발' %}">
        <div class="d-flex align-items-center gap-2">
          <i class="bi bi-code-slash"></i>
          <span>개발</span>
        </div>
      </a>
    </li>
    <li class="mb-3 fs-5 ps-3 py-2 rounded-start-pill">
      <a href="{% url 'posts:category' 'CS' %}">
        <div class="d-flex align-items-center gap-2">
          <i class="bi bi-motherboard"></i>
          <span>CS</span>
        </div>
      </a>
    </li>
    <li class="mb-3 fs-5 ps-3 py-2 rounded-start-pill">
      <a href="{% url 'posts:category' '신기술' %}">
        <div class="d-flex align-items-center gap-2">
          <i class="bi bi-lightbulb"></i>
          <span>신기술</span>
        </div>
      </a>
    </li>
  </ul>
</div>