developer_share_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
]

posts/urls.py
from django.urls import path
from . import views


app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:post_pk>/', views.detail, name='detail'),
    path('category/<str:subject>', views.category, name='category'),
    path('<int:post_pk>/update/', views.update, name='update'),
    path('<int:post_pk>/delete/', views.delete, name='delete'),
]

posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    notice = models.BooleanField(default=False)
    title = models.CharField(max_length=80)
    content = models.TextField()
    category = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    is_new = models.BooleanField(default=False)

posts/forms.py
from django import forms
from .models import Post

CATEGORY_CHOICES = [
    ('개발', '개발'),
    ('CS', 'CS'),
    ('신기술', '신기술'),
]

class PostForm(forms.ModelForm):
    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': '제목을 입력해주세요',
            }
        ),
    )
    content = forms.CharField(
        label='내용',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': '내용을 입력해주세요',
            }
        ),
    )
    category = forms.CharField(
        label='카테고리',
        widget=forms.Select(
            attrs={
                'class': 'form-select',
                'placeholder': '카테고리',
            },
            choices=CATEGORY_CHOICES
        ),
    )
    notice = forms.BooleanField(
        label='공지글',
        widget=forms.CheckboxInput(
            attrs={
                'type': 'checkbox',
                'class': 'form-check-input',
                'placeholder': '공지글',
            }
        )
    )
    class Meta:
        model = Post
        fields = ('notice', 'title', 'content', 'category')

posts/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Post
from .forms import PostForm
from datetime import datetime

# Create your views here.


# index
def index(request):
    posts = Post.objects.all().order_by('-pk')
    today = datetime.now().strftime('%Y-%m-%d')
    select_sorting = request.GET.get('select_sorting')
    posts = sorting(posts, select_sorting)
    new_posts(posts)
    context = {
        'today': today,
        'posts': posts,
        'subject': '모든 글',
        'select_sorting': select_sorting,
    }
    return render(request, 'posts/index.html', context)

# 카테고리 filter
def category(request, subject):
    today = datetime.now().strftime('%Y-%m-%d')
    posts = Post.objects.all().filter(category=subject)
    posts2 = Post.objects.all().filter(notice=True)
    posts = posts.union(posts2).order_by('-pk')
    select_sorting = request.GET.get('select_sorting')
    posts = sorting(posts, select_sorting)

    new_posts(posts)

    context = {
        'today': today,
        'posts': posts,
        'subject': subject,
        'select_sorting': select_sorting,
    }
    return render(request, 'posts/index.html', context)

# 정렬
def sorting(queryset, select_sorting):
    if select_sorting == '최신순':
        return queryset.order_by('-pk')
    elif select_sorting == '오래된순':
        return queryset.order_by('pk')
    else:
        return queryset

# new_posts
def new_posts(posts):
    now = timezone.now()
    for post in posts:
        time_diff = now - post.created_at
        if time_diff < timezone.timedelta(hours=10):
            post.is_new = True
        else:
            post.is_new = False



# create
@login_required
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect('posts:detail', post.pk)
    else:
        form = PostForm()
    context = {
        'form': form,
        'subject': '글 작성',
    }

    return render(request, 'posts/create.html', context)

# 상세페이지
@login_required
def detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    context = {
        'post': post,
    }
    return render(request, 'posts/detail.html', context)

# 수정
@login_required
def update(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:detail', post_pk)
    else:
        form = PostForm(instance=post)
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/update.html', context)

# 삭제
@login_required
def delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    post.delete()
    return redirect('posts:index')

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block style %}

{% endblock style %}

{% block content %}
<form action="{% url 'posts:create' %}" method="POST">
  {% csrf_token %}
  {% for field in form %}
  {% if field.name == 'notice' %}
  <div class="ms-1">
    <label class="form-check-label me-2 mb-2">
      공지글
    </label>
    {{ field }}
  </div>
  {% else %}
    <div class="input-group mb-3">
      <span class="input-group-text" id="{{ field.auto_id }}">{{ field.label }}</span>
      {{ field }}
    </div>
    {% endif %}
  {% endfor %}
  <div class="text-end">
    <a class="btn btn-secondary btn" href="{% url 'posts:index' %}">목록</a>
    <input class="btn btn-success" type="submit" value="생성">
  </div>
</form>
{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block style %}
{% endblock style %}

{% block content %}
  <div>
    <div class="mb-1">
      <a class="btn btn-secondary btn-sm" href="{% url 'posts:update' post.pk %}">수정</a>
      <a class="btn btn-secondary btn-sm" href="{% url 'posts:delete' post.pk %}">삭제</a>
    </div>
    <div class="border rounded-3 p-3 mb-1">
      <div class="mb-3 d-flex align-items-center gap-2">
        {% if post.notice %}
        <div><a class="rounded-3 border border-danger p-1 text-danger bg-danger-subtle" href="{% url 'posts:category' post.category %}">공지</a></div>
        {% else %}
        {% endif %}
        <a href="{% url 'posts:category' post.category %}" class="text-success fw-bold">{{ post.category }}</a>
      </div>
      <h2>{{ post.title }}</h2>
      <hr>
      {{ post.content|linebreaksbr }}
    </div>
      <a class="btn btn-secondary btn-sm" href="{% url 'posts:index' %}">목록</a>
  </div>
{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block style %}
#head > span {
  font-weight: bold;
}
{% endblock style %}

{% block content %}

<!-- 정렬 -->
<form method="GET">
  <div class="d-flex justify-content-end align-items-center gap-1 mb-2">
    <select name="select_sorting" id="select_sorting" class="p-1 rounded-1">
      <option value="최신순" {% if select_sorting == '최신순' %}selected{% endif %}>최신순</option>
      <option value="오래된순" {% if select_sorting == '오래된순' %}selected{% endif %}>오래된순</option>
    </select>
    <input type="submit" class="btn btn-secondary btn-sm" value="정렬">
  </div>
</form>

<!-- 게시판 -->
<div id="head" class="row mb-3">
  <span class="col-1">카테고리</span>
  <span class="col-9 text-center">제목</span>
  <span class="col-2 text-end">작성일</span>
</div>
  <!--공지 글-->
  
  {% for post in posts %}
    {% if post.notice %}
    <div class="row bg-body-secondary py-2 border-top border-bottom">
      <div class="col-1"><a class="rounded-3 border border-danger p-1 text-danger bg-danger-subtle" href="{% url 'posts:category' post.category %}">공지</a></div>
      <span class="col-9"><a href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a></span>
      
      {% now "Y-m-d" as today %}
      {% if today == post.created_at|date:'Y-m-d' %}
        {% if post.is_new %}
        <span class="col-1 text-end new">new</span>
        <span class="col-1 text-end">{{ post.created_at|date:'H:i' }}</span>
        {% else %}
        <span class="col-2 text-end">{{ post.created_at|date:'H:i' }}</span>
        {% endif %}
      {% else %}
        <span class="col-2 text-end">{{ post.created_at|date:'Y-m-d' }}</span>
      {% endif %}
    </div>
    {% endif %}
  {% endfor %}
  
  <!--일반 글-->
  {% for post in posts %}
  {% if not post.notice %}
  <div class="row py-2 border-top border-bottom">
    <span class="col-1"><a href="{% url 'posts:category' post.category %}">{{ post.category }}</a></span>
    <span class="col-9"><a href="{% url 'posts:detail' post.pk %}">{{ post.title }}</a></span>
    
    {% now "Y-m-d" as today %}
    {% if today == post.created_at|date:'Y-m-d' %}
      {% if post.is_new %}
      <span class="col-1 text-end new">new</span>
      <span class="col-1 text-end">{{ post.created_at|date:'H:i' }}</span>
      {% else %}
      <span class="col-2 text-end">{{ post.created_at|date:'H:i' }}</span>
      {% endif %}
    {% else %}
      <span class="col-2 text-end">{{ post.created_at|date:'Y-m-d' }}</span>
    {% endif %}
  </div>
  {% endif %}
  {% endfor %}

  <script>
    const newElements = document.querySelectorAll('.new')
  
    newElements.forEach((el) => {
      setInterval(() => {
        el.classList.toggle('text-danger')
      }, 800)
    })
  </script>
{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block style %}

{% endblock style %}

{% block content %}
<form action="{% url 'posts:update' post.pk %}" method="POST">
  {% csrf_token %}
  {% for field in form %}
  {% if field.name == 'notice' %}
  <div class="ms-1">
    <label class="form-check-label me-2 mb-2">
      공지글
    </label>
    {{ field }}
  </div>
  {% else %}
  <div class="input-group mb-3">
    <span class="input-group-text" aria-label="{{ field.help_text }}" id="{{ field.auto_id }}">{{ field.label }}</span>
    {{ field }}
  </div>
  {% endif %}
  {% endfor %}
  <div class="text-end">
    <a class="btn btn-secondary btn" href="{% url 'posts:index' %}">목록</a>
    <input class="btn btn-success" type="submit" value="수정">
  </div>
</form>
{% endblock content %}